#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
 
set -x

wclean libso thermFunModels
wclean libso constitutiveEquations
wclean libso gaussDefCmpwConvectionScheme
wclean libso boundaryConditions
wclean libso postProcessing/postProcUtils

