#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_DIR/scripts/AllwmakeParseArguments

set -x

wmake libso thermFunModels
wmake libso constitutiveEquations
wmake libso gaussDefCmpwConvectionScheme
wmake libso boundaryConditions
wmake libso postProcessing/postProcUtils

