#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

mkdir -p 0
cp -r 0.orig/* 0/

runApplication blockMesh

runApplication $application

runApplication postProcess -func sampleDict
