#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

rm -rf 0
cp -r 0.orig 0

runApplication blockMesh
runApplication funkySetFields -field T -time 0 -expression "300 * (1 + (pow(pos().x/(max(pos().x) - min(pos().x)),2) + pow(pos().y/(max(pos().y) - min(pos().y)),2)))"

runApplication $application

